# file generated by vcs-versioning
# don't change, don't track in version control

__version__ = version = '0.10.0rc2.dev0+gdbf0f64b1.d20260524'
__version_tuple__ = version_tuple = (0, 10, 0, 'rc2', 'dev0', 'gdbf0f64b1.d20260524')
__commit_id__ = commit_id = None
